on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Generate
      uses: skx/github-action-build@master
      with:
        builder: .github/wasm_build.sh
