name: WebAssembly Module

on:
  push:
    branches: [ "main" ]

env:
  NODE_VERSION: 16
  EMSDK_VERSION: 3.1.26

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{ env.EMSDK_VERSION }}

    - name: Verify Emcc
      run: emcc -v

    - run: make wasm

    - name: install
      run: npm ci

    - name: test
      run: npm test

    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: fasttext-wasm
    #     path: |
    #       webassembly/fasttext.js
    #       webassembly/fasttext_wasm.wasm
    #       webassembly/fasttext_wasm.js
