name: WebAssembly Module

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: 1.38.40

    - name: Verify Emcc
      run: emcc -v
