name: WebAssembly Module

on:
  push:
    branches: [ "main" ]

env:
  EM_VERSION: 3.1.26

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{ env.EM_VERSION }}

    - name: Verify Emcc
      run: emcc -v

    - run: make wasm

    - name: test
      run: npm test

    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: fasttext-wasm
    #     path: |
    #       webassembly/fasttext.js
    #       webassembly/fasttext_wasm.wasm
    #       webassembly/fasttext_wasm.js
